import { Case } from '../types/case';
import { mockCauseList } from './mockApi';

// The backend URL can be configured via environment variable or defaults to relative path / proxy
const BACKEND_BASE_URL = (import.meta as any).env?.VITE_API_URL || '';

export interface AuditEventPayload {
  timestamp: string;
  magistrate_court: string;
  case_id: string;
  action_type: 'VIEW_DOCKET' | 'GENERATED_MEMO' | 'ISSUED_IO_INQUIRY' | 'INITIATED_JUDICIAL_REVIEW' | 'DLSA_REFERRAL';
  milestone?: string;
  status?: string;
  meta?: Record<string, any>;
}

/**
 * MODULE 2 & 1 INTEGRATION:
 * Fetches the daily cause list processed by the Deterministic Compliance Engine.
 * Implements automatic offline fallback to local synthetic data for taluka court resilience (Module 5).
 */
export const fetchCauseList = async (): Promise<Case[]> => {
  try {
    const url = BACKEND_BASE_URL ? `${BACKEND_BASE_URL}/api/cause-list` : '/api/cause-list';
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();
    if (Array.isArray(data) && data.length > 0) {
      // Store in local edge cache for offline resilience
      localStorage.setItem('remindtrack_cached_causelist', JSON.stringify(data));
      return data;
    }
    return mockCauseList;
  } catch (error) {
    console.warn('[RemindTrack Edge Logger] Backend unreachable. Falling back to edge cache or synthetic mock data.', error);
    const cached = localStorage.getItem('remindtrack_cached_causelist');
    if (cached) {
      try {
        return JSON.parse(cached);
      } catch (e) {
        // ignore parse error
      }
    }
    return mockCauseList;
  }
};

export type JudicialDocumentType = 'judicial_review' | 'memo' | 'io_inquiry' | 'dlsa' | 'dlsa_packet';

/**
 * MODULE 4 INTEGRATION:
 * Calls the 1-Click Judicial Document Engine to compile printable review memos,
 * IO inquiries, or DLSA referral packages.
 */
export const requestJudicialDocument = async (
  documentType: JudicialDocumentType,
  caseItem: Case
): Promise<{ success: boolean; downloadUrl?: string; message: string; fallbackText?: string }> => {
  try {
    const url = BACKEND_BASE_URL ? `${BACKEND_BASE_URL}/api/generate-document` : '/api/generate-document';
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        doc_type: documentType,
        case: caseItem,
        case_id: caseItem.case_id,
        docket_no: caseItem.docket_no,
        accused_name: caseItem.accused_name,
        offence_section: caseItem.sections || caseItem.offence_section,
        custody_days: caseItem.custody_days,
        maximum_sentence_days: caseItem.maximum_sentence_days,
        statutory_ref: caseItem.compliance.statutory_ref,
        milestone: caseItem.compliance.milestone,
        court_name: caseItem.court_name,
        jail_location: caseItem.jail_location,
        police_station: caseItem.police_station,
        remand_date: caseItem.remand_date,
      }),
    });

    if (response.ok) {
      const result = await response.json();
      return {
        success: true,
        downloadUrl: result.download_url,
        message: result.message || 'Judicial order package generated by Document Engine.',
      };
    }
    throw new Error('Document generation backend not connected');
  } catch (error) {
    console.info('[RemindTrack Module 4 Hook] Backend generation pending. Emulating client-side memo preview.');
    return {
      success: true,
      message: `Document compiled for ${caseItem.accused_name} (${caseItem.docket_no || caseItem.case_id}).`,
      fallbackText: `ORDER SHEET / MEMO\nCase: ${caseItem.docket_no || caseItem.case_id}\nAccused: ${caseItem.accused_name}\nCustody: ${caseItem.custody_days} Days\nProvision: ${caseItem.compliance.statutory_ref || 'Sec 479 BNSS'}`,
    };
  }
};

/**
 * MODULE 5 INTEGRATION:
 * Sends judicial audit events to the SQLite Audit Trail & Edge Cache Logger.
 * Guarantees local storage persistence if offline.
 */
export const emitAuditEvent = async (event: AuditEventPayload): Promise<void> => {
  // 1. Edge logging (offline-safe local cache)
  const existingAuditRaw = localStorage.getItem('remindtrack_audit_logs');
  const existingAudit: AuditEventPayload[] = existingAuditRaw ? JSON.parse(existingAuditRaw) : [];
  existingAudit.unshift(event);
  localStorage.setItem('remindtrack_audit_logs', JSON.stringify(existingAudit.slice(0, 100)));

  // 2. Transmit to backend SQLite Audit Logger
  try {
    const url = BACKEND_BASE_URL ? `${BACKEND_BASE_URL}/api/audit-log` : '/api/audit-log';
    await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(event),
    });
  } catch (error) {
    console.info('[RemindTrack Edge Cache] Audit event saved locally on edge storage.');
  }
};
