"""
Mock undertrial case data for REMANDTRACK Module 4 demonstration.
15 cases covering all 3 alert types.
"""

from datetime import date

CASES = [
    # ── Alert Type: IO_DELAY (chargesheet not filed within 60 days) ───────────
    {
        "case_id": "RC-2024-001",
        "prisoner_name": "Ramesh Kumar Singh",
        "age": 34,
        "fir_no": "FIR/2024/0312",
        "sections": "IPC § 302, § 34",
        "offence": "Murder",
        "court": "Sessions Court, Patna",
        "judge_name": "Hon. Justice A.K. Verma",
        "io_name": "SI Mahendra Pratap",
        "io_rank": "Sub-Inspector",
        "police_station": "Gardanibagh PS, Patna",
        "days_in_custody": 74,
        "max_sentence_days": 3650,  # 10 years
        "chargesheet_filed": False,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Sunita Devi",
        "alert_type": "IO_DELAY",
        "date_of_arrest": "2024-06-17",
        "prison": "Beur Central Jail, Patna",
    },
    {
        "case_id": "RC-2024-002",
        "prisoner_name": "Mohammed Irfan",
        "age": 28,
        "fir_no": "FIR/2024/0451",
        "sections": "NDPS § 20(b)(ii)(C)",
        "offence": "Possession of Narcotic Drugs",
        "court": "Special NDPS Court, Patna",
        "judge_name": "Hon. Justice B.P. Sinha",
        "io_name": "ASI Rajendra Yadav",
        "io_rank": "Assistant Sub-Inspector",
        "police_station": "Phulwari PS, Patna",
        "days_in_custody": 68,
        "max_sentence_days": 3650,
        "chargesheet_filed": False,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Rakesh Tiwari",
        "alert_type": "IO_DELAY",
        "date_of_arrest": "2024-06-23",
        "prison": "Beur Central Jail, Patna",
    },
    {
        "case_id": "RC-2024-003",
        "prisoner_name": "Suresh Paswan",
        "age": 45,
        "fir_no": "FIR/2024/0198",
        "sections": "IPC § 379, § 411",
        "offence": "Theft & Receiving Stolen Property",
        "court": "CJM Court, Muzaffarpur",
        "judge_name": "Hon. Justice P.K. Tripathi",
        "io_name": "HC Dinesh Ram",
        "io_rank": "Head Constable",
        "police_station": "Sadar PS, Muzaffarpur",
        "days_in_custody": 63,
        "max_sentence_days": 1095,  # 3 years
        "chargesheet_filed": False,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "IO_DELAY",
        "date_of_arrest": "2024-06-28",
        "prison": "Muzaffarpur District Jail",
    },
    {
        "case_id": "RC-2024-004",
        "prisoner_name": "Vikram Tiwari",
        "age": 52,
        "fir_no": "FIR/2024/0523",
        "sections": "IPC § 420, § 467, § 468",
        "offence": "Cheating & Forgery",
        "court": "CJM Court, Gaya",
        "judge_name": "Hon. Justice R.N. Mishra",
        "io_name": "SI Shyamlal Gupta",
        "io_rank": "Sub-Inspector",
        "police_station": "Civil Lines PS, Gaya",
        "days_in_custody": 71,
        "max_sentence_days": 2555,  # 7 years
        "chargesheet_filed": False,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Priya Sharma",
        "alert_type": "IO_DELAY",
        "date_of_arrest": "2024-06-20",
        "prison": "Gaya Central Jail",
    },
    {
        "case_id": "RC-2024-005",
        "prisoner_name": "Ajay Kumar Mandal",
        "age": 38,
        "fir_no": "FIR/2024/0677",
        "sections": "IPC § 326, § 34",
        "offence": "Causing Grievous Hurt by Dangerous Weapon",
        "court": "Sessions Court, Bhagalpur",
        "judge_name": "Hon. Justice S.K. Jha",
        "io_name": "SI Pradeep Kumar",
        "io_rank": "Sub-Inspector",
        "police_station": "Tatarpur PS, Bhagalpur",
        "days_in_custody": 82,
        "max_sentence_days": 2555,
        "chargesheet_filed": False,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "IO_DELAY",
        "date_of_arrest": "2024-06-09",
        "prison": "Bhagalpur Central Jail",
    },
    # ── Alert Type: DLSA_REQUIRED (unrepresented, >50% max sentence served) ──
    {
        "case_id": "RC-2024-006",
        "prisoner_name": "Lal Bahadur Thakur",
        "age": 61,
        "fir_no": "FIR/2023/1102",
        "sections": "IPC § 304, § 34",
        "offence": "Culpable Homicide Not Amounting to Murder",
        "court": "Sessions Court, Darbhanga",
        "judge_name": "Hon. Justice M.K. Rai",
        "io_name": "SI Arvind Mishra",
        "io_rank": "Sub-Inspector",
        "police_station": "Laheriasarai PS, Darbhanga",
        "days_in_custody": 548,
        "max_sentence_days": 1095,
        "chargesheet_filed": True,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "DLSA_REQUIRED",
        "date_of_arrest": "2023-01-30",
        "prison": "Darbhanga District Jail",
    },
    {
        "case_id": "RC-2024-007",
        "prisoner_name": "Poonam Devi",
        "age": 42,
        "fir_no": "FIR/2023/0876",
        "sections": "IPC § 498A, § 304B",
        "offence": "Dowry Death",
        "court": "Sessions Court, Muzaffarpur",
        "judge_name": "Hon. Justice P.K. Tripathi",
        "io_name": "SI Meena Kumari",
        "io_rank": "Sub-Inspector",
        "police_station": "Women PS, Muzaffarpur",
        "days_in_custody": 410,
        "max_sentence_days": 730,
        "chargesheet_filed": True,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "DLSA_REQUIRED",
        "date_of_arrest": "2023-07-17",
        "prison": "Muzaffarpur District Jail",
    },
    {
        "case_id": "RC-2024-008",
        "prisoner_name": "Deepak Sah",
        "age": 23,
        "fir_no": "FIR/2023/1441",
        "sections": "IPC § 307",
        "offence": "Attempt to Murder",
        "court": "Sessions Court, Ara",
        "judge_name": "Hon. Justice V.K. Pandey",
        "io_name": "ASI Rajesh Yadav",
        "io_rank": "Assistant Sub-Inspector",
        "police_station": "Sadar PS, Ara",
        "days_in_custody": 365,
        "max_sentence_days": 730,
        "chargesheet_filed": True,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "DLSA_REQUIRED",
        "date_of_arrest": "2023-09-01",
        "prison": "Ara District Jail",
    },
    {
        "case_id": "RC-2024-009",
        "prisoner_name": "Santosh Kumar Ojha",
        "age": 55,
        "fir_no": "FIR/2022/0912",
        "sections": "IPC § 406, § 420",
        "offence": "Criminal Breach of Trust & Cheating",
        "court": "CJM Court, Saran",
        "judge_name": "Hon. Justice R.C. Shukla",
        "io_name": "SI Umesh Pandey",
        "io_rank": "Sub-Inspector",
        "police_station": "Chhapra PS, Saran",
        "days_in_custody": 620,
        "max_sentence_days": 1095,
        "chargesheet_filed": True,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "DLSA_REQUIRED",
        "date_of_arrest": "2022-12-19",
        "prison": "Chhapra District Jail",
    },
    {
        "case_id": "RC-2024-010",
        "prisoner_name": "Guddu Yadav",
        "age": 19,
        "fir_no": "FIR/2023/1789",
        "sections": "POCSO § 4, IPC § 376",
        "offence": "Penetrative Sexual Assault",
        "court": "Special POCSO Court, Patna",
        "judge_name": "Hon. Justice A.K. Verma",
        "io_name": "SI Kavita Singh",
        "io_rank": "Sub-Inspector",
        "police_station": "Patrakar Nagar PS, Patna",
        "days_in_custody": 270,
        "max_sentence_days": 365,
        "chargesheet_filed": True,
        "legal_aid_assigned": False,
        "legal_aid_advocate": None,
        "alert_type": "DLSA_REQUIRED",
        "date_of_arrest": "2023-12-04",
        "prison": "Beur Central Jail, Patna",
    },
    # ── Alert Type: SATURATION (100% max sentence served as undertrial) ───────
    {
        "case_id": "RC-2024-011",
        "prisoner_name": "Shyam Sundar Prasad",
        "age": 49,
        "fir_no": "FIR/2021/0342",
        "sections": "IPC § 323, § 341",
        "offence": "Voluntarily Causing Hurt & Wrongful Restraint",
        "court": "CJM Court, Patna",
        "judge_name": "Hon. Justice A.K. Verma",
        "io_name": "HC Suresh Kumar",
        "io_rank": "Head Constable",
        "police_station": "Kankarbagh PS, Patna",
        "days_in_custody": 365,
        "max_sentence_days": 365,
        "chargesheet_filed": True,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Om Prakash",
        "alert_type": "SATURATION",
        "date_of_arrest": "2021-09-01",
        "prison": "Beur Central Jail, Patna",
    },
    {
        "case_id": "RC-2024-012",
        "prisoner_name": "Nitesh Kumar Choudhary",
        "age": 33,
        "fir_no": "FIR/2021/0891",
        "sections": "IPC § 379",
        "offence": "Theft",
        "court": "CJM Court, Gaya",
        "judge_name": "Hon. Justice R.N. Mishra",
        "io_name": "SI Binod Singh",
        "io_rank": "Sub-Inspector",
        "police_station": "Bodh Gaya PS, Gaya",
        "days_in_custody": 730,
        "max_sentence_days": 730,
        "chargesheet_filed": True,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Alok Kumar",
        "alert_type": "SATURATION",
        "date_of_arrest": "2021-09-01",
        "prison": "Gaya Central Jail",
    },
    {
        "case_id": "RC-2024-013",
        "prisoner_name": "Arun Kumar Dubey",
        "age": 41,
        "fir_no": "FIR/2020/1122",
        "sections": "IPC § 406",
        "offence": "Criminal Breach of Trust",
        "court": "CJM Court, Vaishali",
        "judge_name": "Hon. Justice S.N. Tripathi",
        "io_name": "SI Dinesh Sah",
        "io_rank": "Sub-Inspector",
        "police_station": "Hajipur PS, Vaishali",
        "days_in_custody": 1095,
        "max_sentence_days": 1095,
        "chargesheet_filed": True,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Seema Gupta",
        "alert_type": "SATURATION",
        "date_of_arrest": "2020-09-01",
        "prison": "Hajipur District Jail",
    },
    {
        "case_id": "RC-2024-014",
        "prisoner_name": "Rajiv Ranjan Kumar",
        "age": 27,
        "fir_no": "FIR/2022/0455",
        "sections": "IPC § 325, § 34",
        "offence": "Voluntarily Causing Grievous Hurt",
        "court": "CJM Court, Nalanda",
        "judge_name": "Hon. Justice U.K. Pandey",
        "io_name": "ASI Ram Briksh",
        "io_rank": "Assistant Sub-Inspector",
        "police_station": "Bihar Sharif PS, Nalanda",
        "days_in_custody": 548,
        "max_sentence_days": 548,
        "chargesheet_filed": True,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Vinay Kumar",
        "alert_type": "SATURATION",
        "date_of_arrest": "2022-05-01",
        "prison": "Nalanda District Jail",
    },
    {
        "case_id": "RC-2024-015",
        "prisoner_name": "Binod Kumar Ray",
        "age": 58,
        "fir_no": "FIR/2019/0788",
        "sections": "IPC § 420",
        "offence": "Cheating",
        "court": "CJM Court, Sitamarhi",
        "judge_name": "Hon. Justice K.P. Singh",
        "io_name": "SI Anil Kumar",
        "io_rank": "Sub-Inspector",
        "police_station": "Sitamarhi PS",
        "days_in_custody": 2555,
        "max_sentence_days": 2555,
        "chargesheet_filed": True,
        "legal_aid_assigned": True,
        "legal_aid_advocate": "Adv. Ravi Shankar",
        "alert_type": "SATURATION",
        "date_of_arrest": "2019-09-01",
        "prison": "Sitamarhi District Jail",
    },
]

# Index by case_id for O(1) lookup
CASES_BY_ID = {c["case_id"]: c for c in CASES}
